version: '3'

services:
  yolo_con:
    image: my-yolo-app:latest
    container_name: yolo_con
    ports:
      - "8081:8081"
    env_file:
      - secrets.env
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    networks:
      - mongoCluster

  tele_con:
    image: my-tele-bot
    container_name: tele_con
    ports:
      - "8443:8443"
    env_file:
      - secrets.env
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    networks:
      - mongoCluster


  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "27017:27017"
    command: mongod --replSet myReplicaSet --bind_ip_all
    networks:
      - mongoCluster

  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "27018:27017"
    command: mongod --replSet myReplicaSet --bind_ip_all
    networks:
      - mongoCluster

  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - "27019:27017"
    command: mongod --replSet myReplicaSet --bind_ip_all
    networks:
      - mongoCluster

networks:
  mongoCluster:
    driver: bridge